language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential python-setuptools debhelper cdbs python-support

install:
  - pip install setuptools

script: make deb
