language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential debhelper cdbs

install:
  - pip install setuptools

script: make deb
