dist: trusty
language: python
python:
- 2.7_with_system_site_packages
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y build-essential python-setuptools debhelper cdbs dh-python
script: make deb
env:
  global:
    - secure: "JK/Xyt1uBDkyvkfws/5IYDBbM9cYLh0sEp0XKWTjxCgnQ8EqIMin7zpcJNd36/mq3aaNG3IopXE9lEdqiEhG4yWh6H4pgXSm24ChMfICkX74Cp7ctE1qMVt7plVuLjXCtAyEhk1149zIf83KYDHg2GFP99+KmfNm1IjaX7tu4+Xvd8uz7syDPtfQBSR6D67NWQnhKw3wOZ/iAUqxXxaYqb3pux+nI4LiKCWIDplPQV85zqPbwyJZV6Gzx+lDd9vt5pze7ZJ4jLTUlqQiK/gwDoAqIga7Sqah+HKQz2zrWJ8NB6iiW4KifA1Frbu50ch3lqoIQyMNnkSw9b1EyWqnCE47IsZuE6921biYOLV3vqZp4N/C99YX4BvR7msFGs+mOeksmelIlxNK0NjbGReE/zpWlk13zcteOo4V6l6fcKtp8iOYkalqJrUR5cRtVNNNVLGMbbYsxpxkMhRJPbwgLdyFjPnOqAu9WvAXkDa0h2MS5ZJtrCXUM6akbkL/HwSYeV2LC4SbAQI+pQajA0AQOXtzCFWDXCaZGR2t5QwPUMQYYh0849YgkSfcedWnn0k5axT0tGor9COX90ARb21oxmZM1RP41h1XPzbSPsJjZ3S8Jen5dit14bmsNdOlbssuLIJ10Ge/eihmfIJB5BHCvhVtDBpo/PWwaPhW2s+M0PE="
    - secure: "KoZjHPxVlaQdrUGa5rO6tblz7KWmRUVK728Gbbfbygi5oRtutQPV84K/mpDBeAbY+bbEqhRGXgXfVnQ3z9wwi1TaxCBsPVe9LnlBUCfJ8aeMWNo0A63bWZoOKrgu3+gCgdDS2vwY6rKXPgd1vuWu6dsC/xhf+LpBYAd89Tluu+Od+VVi2c5k1CaoBtQ8Ya256k+ImjjfgAW28X12K5JbLEI6K2xXSkZGggOPTh6jFQ6Ea+Ivv58EFXTXVlm2nnO5rpz+V7fCyOAaxWrQ5nHINoYLsb3qHXYJ0+eyTvF8mQCcLXN9SsA1+vvb/GjCUu60tRVWVHwk2CAsT247jCYKX0udXGnOLKpj0qORxXXzhpIItKeqIOEE6cxOkkLhkrCBmmxl/WJB3Np3CxwaDsNYHhY3HFmIXBacj3d/Wm1VSKrdrbXsfa/PxjmQgthdPCdBTyXCYqeVMZwBLt1An8EiPdOUUT6H16WT2DXlrdMr5QUjDnlU+yfimeuY+KnaQCexZc1LwAT1iIM4uYufoUlACmQV16ehm3XUT9Q9WIZqB5Ze0TXG+uqLRxcaHL94Z7E61GEyKlyhI+/GvWpEUZw4xE9flLwhJEAK/iHB1VYCoJEYFBWKwt2prrdXntzW+AMQdf5zoGlP9HkkTHC4AOrphlOR+YSv09WdzOhpMX1vHOo="
before_deploy:
- ls
- ls ../
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VOhySJhtWtd3GUuIcqCsvMpFoFh/rFoL1z9BWwWm2AalddpRPR6KkG62MO0VsIaRcWb3iXJiOCqaq5MNoDJz+6pFEPlE1O/6CEUkhQHhqg6C9sg97a5gAhKU9PQnhzM/KGEmJ/VsVj0Cww8jlQ7+4kfHKumO7OaU5v/+s9mkMZ80iLLxXlmlsuHBxTDwjj/lDW4G310nGiokAAyg07zRHH55QNCGjBCiFpwAL/fMGYzpHHcP9Eck6UO7Eb0RGe7bL0kFJtyjg6J1Q1z/9nkWsrAx0lqNh5EQEYazX1pG2fZPWzcxKH3y+chLl4xODBO9IOJCmnDtcDqjSN51+QBDlCklSnTYsfJZk2ilkinqgTCUcko1SHugCttokiUWEP1jB2m1wbOuVbJLuLpv7h+R4MH2WconUDwGHbU+3CZx5UKogMhXupDOqYDhLftohMNm+otAdvbtMmlCK6wyucfI9WAFkDh6wsgsiDMkWpmCmEg0yGrlUhjTLTy/v5g+YkIfO1MWrCbNbR3reB4B07YuI4a/zTIEeMyfuJ4TVCget/WPqv2W0JygIo7ijBK5Nyh764saEMn20jdyT+GKtiQ1xmMWKwS3wQGyTffDU3zqkDye1sGhvV7rAi9NAUeIdg6czHn8TglPX9cZz+TxLJ3CrGUY1X/lzrlKxq8rgqIc4Ao=
  file_glob: true
  file: "${RELEASE_FILE_NAME}"
  on:
    tags: true
    repo: mariolukas/FabScanPi-Server
after_deploy:
  "curl -T *.deb -u $FTPUSER:$FTPPASSWORD ftp://mariolukas.de/"
