dist: trusty
language: python
python:
- 2.7_with_system_site_packages
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y build-essential python-setuptools debhelper cdbs dh-python python-pip rsync 
before_script: pip install mkdocs
script: make deb
after_success:
- curl -T ../*.deb -u $FTPUSER:$FTPPASSWORD ftp://mariolukas.de/build/
- NOW=`date +%Y-%m-%d-%H-%M`
- mkdocs build
- cd ..
- mkdir tmp
- cd tmp
- git clone -b gh-pages https://github.com/mariolukas/FabScanPi-Server.git
- cd FabScanPi-Server
- git config --global user.email "dev@fabscan.org"
- git config --global user.name "Travis CI"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
- rsync -a -v ../../FabScanPi-Server/site/ .
- git commit -am "travis doc update ${NOW}"
- git push
- cd ../../FabScanPi-Server/
env:
  global:
  - secure: "h1lz0NgCerg0Y6cGxn4qOr/qOs+kwdmXu0MabK6WlDzYoViO38w5XO6i/puxYaN45GV3oLpqg04wE4S67cB+t/VaipOrulgBET6mNTVVh0wC8SqkLUon+whUbphNOHrzrYX1gqT9qWNX/VUvWWSoKmEA+PoY1/9gmhHS68GE0WefFkd3gnNvsPsTF0hklr2DoVtpk8jPZVB033LnLr64mEbwLN8qJyAfYyG9QqQyGA60h1ybG9HryD0cOkdigzRnrAz+HYY2Ze3BhBzLyBJWQ4S5P5t2ScBKlZUfeJLTwsmKqA8H2g0iVcA1J9xnSfXSYrDWITVNti1zB8xdpKh5/STjxNTCFlZAXPg02TP+omTThhP2n2Zr8NM7Pz/VmAvv9MAarQS2JvuA2nyriYezzS9cySLfIckdMN1PoYPTlGTQZDuuxO2+xMuUhroOsb5VeqC9dXgJLPH7uouhOi0LjUBc36PfjPKgL9zEU4MA0xCnlLHsAXDUMsQ6lKg1lBvEiXIVxhCnUdge6/1oC+TsZeFWnkxynA6eKBBxUSTSGuVth9GYzNsrWleEQSNY9lpj9PMr8fbHS5KDRxYSofY1c4DUGXNu2nvih2OgoE4g67sZ/1DKIFgGfbwm9uWcVrMW5BwWk6G+YEIcMdSekC2MXqxStz4OmCzma7cazx67SCs="
  - secure: "o0UJz+f9O1fKc7KaPv9i1JbeSiBv3L/3UXLGElxVGOBWA/1ls5E6oINfhr7h2okQjbjkSUaiwi2yJBGERNFJbic7uhoh9F+S9NHQx3UOfb7beGTb+f705T+fSe2EuNeovla0tclbUJS4rgEBxAjdsQ8fTV5Z1aPrYtMXCvucB3qOT2VXM8fPaBL1wTqgIoVe1fvx6Gk7CdmHrgWKwTmpEfJUMoq08+nNb7KYxz7uXdCX55auLymByC8BkOzf7JoVCKZ39/8wIBMVCkPu+ntunAYlYe0oDqD1it3n3swEiXAC1WwtAroJwGP0W3r0hAvzHw7xWv55xs7az9ju3a/nej29TGyxy42pb78wKwBk6IVRrmWY/7FePsOmpa6FuMB4JLgM14xAvdkh9GZXWbCrNwExMxYe7zh/XHwwRVYh6owJ/nqPfm5+IAjq8vrPSSKHEvuweNyMuX5cguLgCQoetUvdQ9jJrBGq1kQe6Ar/Q2rhTIavyhe+gpo6PsPFxluuatWtl2ylHFZONZVYWYvf2+0n6YyUtFrT5pYad4rsg+HDrl9wqyV/nfbyZDcZxcOqE69MXUct6Y1r7l1emKP0a9O8NpTYlngOSC1KOmPVdtMxIAJfAsJvyOzL5StgPETJCpFRlLORjj/s+QLztg6J0C+iRjhKE4PTCaWRcAIWfcA="
  - secure: "iKV7rjdri+dxUlyr0C01195QFREbfIt0nL1ocdMrxDZdp8hb25pDl3UPrbC8pBSHIfOvbucfN7BMukS4EsD3Jxw0YCInwwUR5hZRZkiegU5TuUdzKHpbSCHl8+gtv9IcQKSYryHeFGAtCnW+52XIlNkLH8pzjKJyLkMB/uIVDdcQn1az7t8MR21ucTJdyGf/oJBmabmq9nwqEgumA+Ei+6J+/jdzK+M3do1iON1yHFJS2yGU21QdRIRxvEIat8Ss6JV/nfWFMbWQH/YRHKTrMXkgscqgDB/hJtfDgIvlObgsssrScRSoOm3a7vKEn4OoefUV0oFsPBrCKYEjWMqyEutz/nX25bV2gytrKbzyurI8Qr1QMJhcFZiobLkhMWTyAS/lJqQl45/Ffxj2pJFiUXvKCz+dwKYaQ/zjAu2ZUhxFw4f7KR7yTz3ifQFHy6imZ/1P/J7LLLiMXENN2xQCP80nsuLdRVFFms3z/nSbm/dLosudWHWu+x0tdbMd9XswfRqcaAr2WePNbGLAzb3mivKoP1hIG7yMVgc6dnLWoH2QPtcSdwSsBkkUZPMMRrk4Hy1GqYGPrqJ+CuHhffRKlnL+Irj3uMO0Uxxl0w/YK6h4UJu6bnvIsLIKNR84ZeoQqm8q10tXOZrlInAYYfYthRumBzNNNeCfneTHeqRL/PI="
before_deploy:
- export RELEASE_FILE_NAME=$(ls ../*.deb)
after_deploy: 
- curl -T ../*.deb -u $FTPUSER:$FTPPASSWORD ftp://mariolukas.de/deploy/
- NOW=`date +%Y-%m-%d-%H-%M`
- cd ..
- git clone https://github.com/mariolukas/FabScanPi-Build-Raspbian.git
- cd FabScanPi-Build-Raspbian
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git tag v.${NOW} -m "new release ${RELEASE_FILE_NAME}"
- git push origin --tags
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
  - secure: "iKV7rjdri+dxUlyr0C01195QFREbfIt0nL1ocdMrxDZdp8hb25pDl3UPrbC8pBSHIfOvbucfN7BMukS4EsD3Jxw0YCInwwUR5hZRZkiegU5TuUdzKHpbSCHl8+gtv9IcQKSYryHeFGAtCnW+52XIlNkLH8pzjKJyLkMB/uIVDdcQn1az7t8MR21ucTJdyGf/oJBmabmq9nwqEgumA+Ei+6J+/jdzK+M3do1iON1yHFJS2yGU21QdRIRxvEIat8Ss6JV/nfWFMbWQH/YRHKTrMXkgscqgDB/hJtfDgIvlObgsssrScRSoOm3a7vKEn4OoefUV0oFsPBrCKYEjWMqyEutz/nX25bV2gytrKbzyurI8Qr1QMJhcFZiobLkhMWTyAS/lJqQl45/Ffxj2pJFiUXvKCz+dwKYaQ/zjAu2ZUhxFw4f7KR7yTz3ifQFHy6imZ/1P/J7LLLiMXENN2xQCP80nsuLdRVFFms3z/nSbm/dLosudWHWu+x0tdbMd9XswfRqcaAr2WePNbGLAzb3mivKoP1hIG7yMVgc6dnLWoH2QPtcSdwSsBkkUZPMMRrk4Hy1GqYGPrqJ+CuHhffRKlnL+Irj3uMO0Uxxl0w/YK6h4UJu6bnvIsLIKNR84ZeoQqm8q10tXOZrlInAYYfYthRumBzNNNeCfneTHeqRL/PI="
  file_glob: true
  file: "${RELEASE_FILE_NAME}"
  on:
    tags: true
    repo: mariolukas/FabScanPi-Server
