dist: trusty
language: python
python:
  - "2.7_with_system_site_packages"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential python-setuptools debhelper cdbs dh-python
script: make deb
