site_name: FabScanPi
pages:
- Home: index.md
- News: news.md
- Examples: examples.md
- Hardware: hardware.md
- Software: software.md
- Developing: developing.md
- Contributing: contributing.md
- Community: community.md
- F.A.Q: faq.md
extra_css:
  - css/extra.css
extra_javascript:
  - js/main.js
theme: readthedocs
theme_dir: docs-theme
extra:
    version: 1.0
repo_url: https://github.com/mariolukas/FabScanPi-Server
site_author: Mario Lukas
site_favicon: images/fabscanpi_ICON.png
copyright: © Copyright 2015-2016, Mario Lukas
site_description: FabScan is a Raspberry Pi based, standalone web-enabled open source 3D laser scanner.